// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSI.Data;

#nullable disable

namespace PSI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824094017_SeedDemoData")]
    partial class SeedDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "苏州市相城区XX路100号",
                            ContactPerson = "刘厂长",
                            Name = "宏达机械制造厂",
                            Phone = "13600004444"
                        },
                        new
                        {
                            Id = 2,
                            Address = "东莞市塘厦镇XX路3号",
                            ContactPerson = "陈工",
                            Name = "蓝天包装设备公司",
                            Phone = "13500005555"
                        },
                        new
                        {
                            Id = 3,
                            Address = "武汉市汉阳区XX路21号",
                            ContactPerson = "赵工",
                            Name = "恒信水处理工程",
                            Phone = "13400006666"
                        },
                        new
                        {
                            Id = 4,
                            Address = "广州市番禺区XX路18号",
                            ContactPerson = "黄工",
                            Name = "广州明辉食品机械",
                            Phone = "13044441111"
                        },
                        new
                        {
                            Id = 5,
                            Address = "青岛市黄岛区XX路77号",
                            ContactPerson = "郑工",
                            Name = "青岛海纳重工装备",
                            Phone = "12855552222"
                        },
                        new
                        {
                            Id = 6,
                            Address = "成都市高新区XX路32号",
                            ContactPerson = "何工",
                            Name = "成都锦程自动化集成",
                            Phone = "12766663333"
                        });
                });

            modelBuilder.Entity("PSI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "控制器",
                            Name = "PLC 模块 CPU1214C",
                            PurchasePrice = 1500m,
                            SalePrice = 1850m,
                            Unit = "台"
                        },
                        new
                        {
                            Id = 2,
                            Category = "人机界面",
                            Name = "触摸屏 TP700",
                            PurchasePrice = 2200m,
                            SalePrice = 2680m,
                            Unit = "台"
                        },
                        new
                        {
                            Id = 3,
                            Category = "驱动",
                            Name = "变频器 0.75kW",
                            PurchasePrice = 680m,
                            SalePrice = 890m,
                            Unit = "台"
                        },
                        new
                        {
                            Id = 4,
                            Category = "传感器",
                            Name = "接近开关 PNP NO",
                            PurchasePrice = 35m,
                            SalePrice = 58m,
                            Unit = "个"
                        },
                        new
                        {
                            Id = 5,
                            Category = "传感器",
                            Name = "光电传感器对射",
                            PurchasePrice = 62m,
                            SalePrice = 95m,
                            Unit = "个"
                        },
                        new
                        {
                            Id = 6,
                            Category = "低压电器",
                            Name = "中间继电器 24VDC",
                            PurchasePrice = 18m,
                            SalePrice = 30m,
                            Unit = "个"
                        },
                        new
                        {
                            Id = 7,
                            Category = "线材",
                            Name = "屏蔽双绞线",
                            PurchasePrice = 3.5m,
                            SalePrice = 6m,
                            Unit = "米"
                        },
                        new
                        {
                            Id = 8,
                            Category = "电源",
                            Name = "开关电源 24V 5A",
                            PurchasePrice = 85m,
                            SalePrice = 130m,
                            Unit = "个"
                        },
                        new
                        {
                            Id = 9,
                            Category = "驱动",
                            Name = "伺服电机 750W",
                            PurchasePrice = 1350m,
                            SalePrice = 1750m,
                            Unit = "台"
                        },
                        new
                        {
                            Id = 10,
                            Category = "线材",
                            Name = "编码器线缆 2米",
                            PurchasePrice = 45m,
                            SalePrice = 75m,
                            Unit = "根"
                        },
                        new
                        {
                            Id = 11,
                            Category = "低压电器",
                            Name = "空气开关 2P 32A",
                            PurchasePrice = 28m,
                            SalePrice = 48m,
                            Unit = "个"
                        },
                        new
                        {
                            Id = 12,
                            Category = "传感器",
                            Name = "光电开关漫反射",
                            PurchasePrice = 55m,
                            SalePrice = 88m,
                            Unit = "个"
                        },
                        new
                        {
                            Id = 13,
                            Category = "软件",
                            Name = "组态软件授权",
                            PurchasePrice = 800m,
                            SalePrice = 1200m,
                            Unit = "套"
                        },
                        new
                        {
                            Id = 14,
                            Category = "通讯",
                            Name = "工业交换机 8口",
                            PurchasePrice = 160m,
                            SalePrice = 260m,
                            Unit = "台"
                        },
                        new
                        {
                            Id = 15,
                            Category = "低压电器",
                            Name = "信号隔离器",
                            PurchasePrice = 65m,
                            SalePrice = 105m,
                            Unit = "个"
                        },
                        new
                        {
                            Id = 16,
                            Category = "低压电器",
                            Name = "急停按钮盒",
                            PurchasePrice = 22m,
                            SalePrice = 40m,
                            Unit = "个"
                        });
                });

            modelBuilder.Entity("PSI.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2026, 4, 8, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260408093000",
                            SupplierId = 3,
                            TotalAmount = 36360m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2026, 5, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260512090000",
                            SupplierId = 1,
                            TotalAmount = 16650m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2026, 6, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260615093000",
                            SupplierId = 5,
                            TotalAmount = 17660m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2026, 7, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260718090000",
                            SupplierId = 4,
                            TotalAmount = 22200m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 8, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2026, 8, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260810093000",
                            SupplierId = 2,
                            TotalAmount = 34740m
                        });
                });

            modelBuilder.Entity("PSI.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 15000m,
                            ProductId = 1,
                            PurchaseOrderId = 1,
                            Quantity = 10,
                            UnitPrice = 1500m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 13200m,
                            ProductId = 2,
                            PurchaseOrderId = 1,
                            Quantity = 6,
                            UnitPrice = 2200m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 8160m,
                            ProductId = 3,
                            PurchaseOrderId = 1,
                            Quantity = 12,
                            UnitPrice = 680m
                        },
                        new
                        {
                            Id = 4,
                            Amount = 7000m,
                            ProductId = 4,
                            PurchaseOrderId = 2,
                            Quantity = 200,
                            UnitPrice = 35m
                        },
                        new
                        {
                            Id = 5,
                            Amount = 5400m,
                            ProductId = 6,
                            PurchaseOrderId = 2,
                            Quantity = 300,
                            UnitPrice = 18m
                        },
                        new
                        {
                            Id = 6,
                            Amount = 4250m,
                            ProductId = 8,
                            PurchaseOrderId = 2,
                            Quantity = 50,
                            UnitPrice = 85m
                        },
                        new
                        {
                            Id = 7,
                            Amount = 9300m,
                            ProductId = 5,
                            PurchaseOrderId = 3,
                            Quantity = 150,
                            UnitPrice = 62m
                        },
                        new
                        {
                            Id = 8,
                            Amount = 6600m,
                            ProductId = 12,
                            PurchaseOrderId = 3,
                            Quantity = 120,
                            UnitPrice = 55m
                        },
                        new
                        {
                            Id = 9,
                            Amount = 1760m,
                            ProductId = 16,
                            PurchaseOrderId = 3,
                            Quantity = 80,
                            UnitPrice = 22m
                        },
                        new
                        {
                            Id = 10,
                            Amount = 7500m,
                            ProductId = 1,
                            PurchaseOrderId = 4,
                            Quantity = 5,
                            UnitPrice = 1500m
                        },
                        new
                        {
                            Id = 11,
                            Amount = 10800m,
                            ProductId = 9,
                            PurchaseOrderId = 4,
                            Quantity = 8,
                            UnitPrice = 1350m
                        },
                        new
                        {
                            Id = 12,
                            Amount = 3900m,
                            ProductId = 15,
                            PurchaseOrderId = 4,
                            Quantity = 60,
                            UnitPrice = 65m
                        },
                        new
                        {
                            Id = 13,
                            Amount = 3500m,
                            ProductId = 7,
                            PurchaseOrderId = 5,
                            Quantity = 1000,
                            UnitPrice = 3.5m
                        },
                        new
                        {
                            Id = 14,
                            Amount = 9000m,
                            ProductId = 10,
                            PurchaseOrderId = 5,
                            Quantity = 200,
                            UnitPrice = 45m
                        },
                        new
                        {
                            Id = 15,
                            Amount = 2240m,
                            ProductId = 11,
                            PurchaseOrderId = 5,
                            Quantity = 80,
                            UnitPrice = 28m
                        },
                        new
                        {
                            Id = 16,
                            Amount = 16000m,
                            ProductId = 13,
                            PurchaseOrderId = 5,
                            Quantity = 20,
                            UnitPrice = 800m
                        },
                        new
                        {
                            Id = 17,
                            Amount = 4000m,
                            ProductId = 14,
                            PurchaseOrderId = 5,
                            Quantity = 25,
                            UnitPrice = 160m
                        });
                });

            modelBuilder.Entity("PSI.Models.SaleOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.ToTable("SaleOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 5, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260520093000",
                            TotalAmount = 14850m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260625090000",
                            TotalAmount = 15280m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260728090000",
                            TotalAmount = 11700m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 8, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 8, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260815090000",
                            TotalAmount = 15850m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 8, 22, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 6,
                            OrderDate = new DateTime(2026, 8, 22, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260822093000",
                            TotalAmount = 14190m
                        });
                });

            modelBuilder.Entity("PSI.Models.SaleOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleOrderId");

                    b.ToTable("SaleOrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 7400m,
                            ProductId = 1,
                            Quantity = 4,
                            SaleOrderId = 1,
                            UnitPrice = 1850m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 4450m,
                            ProductId = 3,
                            Quantity = 5,
                            SaleOrderId = 1,
                            UnitPrice = 890m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 3000m,
                            ProductId = 6,
                            Quantity = 100,
                            SaleOrderId = 1,
                            UnitPrice = 30m
                        },
                        new
                        {
                            Id = 4,
                            Amount = 8040m,
                            ProductId = 2,
                            Quantity = 3,
                            SaleOrderId = 2,
                            UnitPrice = 2680m
                        },
                        new
                        {
                            Id = 5,
                            Amount = 4640m,
                            ProductId = 4,
                            Quantity = 80,
                            SaleOrderId = 2,
                            UnitPrice = 58m
                        },
                        new
                        {
                            Id = 6,
                            Amount = 2600m,
                            ProductId = 8,
                            Quantity = 20,
                            SaleOrderId = 2,
                            UnitPrice = 130m
                        },
                        new
                        {
                            Id = 7,
                            Amount = 5700m,
                            ProductId = 5,
                            Quantity = 60,
                            SaleOrderId = 3,
                            UnitPrice = 95m
                        },
                        new
                        {
                            Id = 8,
                            Amount = 4400m,
                            ProductId = 12,
                            Quantity = 50,
                            SaleOrderId = 3,
                            UnitPrice = 88m
                        },
                        new
                        {
                            Id = 9,
                            Amount = 1600m,
                            ProductId = 16,
                            Quantity = 40,
                            SaleOrderId = 3,
                            UnitPrice = 40m
                        },
                        new
                        {
                            Id = 10,
                            Amount = 8750m,
                            ProductId = 9,
                            Quantity = 5,
                            SaleOrderId = 4,
                            UnitPrice = 1750m
                        },
                        new
                        {
                            Id = 11,
                            Amount = 2600m,
                            ProductId = 14,
                            Quantity = 10,
                            SaleOrderId = 4,
                            UnitPrice = 260m
                        },
                        new
                        {
                            Id = 12,
                            Amount = 4500m,
                            ProductId = 10,
                            Quantity = 60,
                            SaleOrderId = 4,
                            UnitPrice = 75m
                        },
                        new
                        {
                            Id = 13,
                            Amount = 9600m,
                            ProductId = 13,
                            Quantity = 8,
                            SaleOrderId = 5,
                            UnitPrice = 1200m
                        },
                        new
                        {
                            Id = 14,
                            Amount = 1440m,
                            ProductId = 11,
                            Quantity = 30,
                            SaleOrderId = 5,
                            UnitPrice = 48m
                        },
                        new
                        {
                            Id = 15,
                            Amount = 3150m,
                            ProductId = 15,
                            Quantity = 30,
                            SaleOrderId = 5,
                            UnitPrice = 105m
                        });
                });

            modelBuilder.Entity("PSI.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 120
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 90
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 1000
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Quantity = 140
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 11,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 12,
                            Quantity = 70
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 13,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 14,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 15,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 16,
                            Quantity = 40
                        });
                });

            modelBuilder.Entity("PSI.Models.StockLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 4, 8, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260408093000",
                            ProductId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 4, 8, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260408093000",
                            ProductId = 2,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 3,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 4, 8, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260408093000",
                            ProductId = 3,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 4,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 5, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260512090000",
                            ProductId = 4,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 5,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 5, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260512090000",
                            ProductId = 6,
                            Quantity = 300
                        },
                        new
                        {
                            Id = 6,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 5, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260512090000",
                            ProductId = 8,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 7,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 6, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260615093000",
                            ProductId = 5,
                            Quantity = 150
                        },
                        new
                        {
                            Id = 8,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 6, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260615093000",
                            ProductId = 12,
                            Quantity = 120
                        },
                        new
                        {
                            Id = 9,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 6, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260615093000",
                            ProductId = 16,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 10,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 7, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260718090000",
                            ProductId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 11,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 7, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260718090000",
                            ProductId = 9,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 12,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 7, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260718090000",
                            ProductId = 15,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 13,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 8, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260810093000",
                            ProductId = 7,
                            Quantity = 1000
                        },
                        new
                        {
                            Id = 14,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 8, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260810093000",
                            ProductId = 10,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 15,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 8, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260810093000",
                            ProductId = 11,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 16,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 8, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260810093000",
                            ProductId = 13,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 17,
                            ChangeType = "采购入库",
                            CreatedAt = new DateTime(2026, 8, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "CG20260810093000",
                            ProductId = 14,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 18,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 5, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260520093000",
                            ProductId = 1,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 19,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 5, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260520093000",
                            ProductId = 3,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 20,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 5, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260520093000",
                            ProductId = 6,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 21,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260625090000",
                            ProductId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 22,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260625090000",
                            ProductId = 4,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 23,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260625090000",
                            ProductId = 8,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 24,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260728090000",
                            ProductId = 5,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 25,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260728090000",
                            ProductId = 12,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 26,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260728090000",
                            ProductId = 16,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 27,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 8, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260815090000",
                            ProductId = 9,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 28,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 8, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260815090000",
                            ProductId = 14,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 29,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 8, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260815090000",
                            ProductId = 10,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 30,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 8, 22, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260822093000",
                            ProductId = 13,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 31,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 8, 22, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260822093000",
                            ProductId = 11,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 32,
                            ChangeType = "销售出库",
                            CreatedAt = new DateTime(2026, 8, 22, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNo = "XS20260822093000",
                            ProductId = 15,
                            Quantity = 30
                        });
                });

            modelBuilder.Entity("PSI.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "上海市闵行区XX路88号",
                            ContactPerson = "王工",
                            Name = "华东工控设备有限公司",
                            Phone = "13800001111"
                        },
                        new
                        {
                            Id = 2,
                            Address = "深圳市宝安区XX路12号",
                            ContactPerson = "李经理",
                            Name = "深圳自动化元器件商行",
                            Phone = "13900002222"
                        },
                        new
                        {
                            Id = 3,
                            Address = "广州市天河区XX路6号",
                            ContactPerson = "张经理",
                            Name = "西门子授权分销商",
                            Phone = "13700003333"
                        },
                        new
                        {
                            Id = 4,
                            Address = "北京市海淀区XX路15号",
                            ContactPerson = "孙工",
                            Name = "北京中科自控设备",
                            Phone = "13311117777"
                        },
                        new
                        {
                            Id = 5,
                            Address = "武汉市东湖高新区XX路9号",
                            ContactPerson = "周工",
                            Name = "武汉光谷传感器科技",
                            Phone = "13222228888"
                        },
                        new
                        {
                            Id = 6,
                            Address = "东莞市长安镇XX路56号",
                            ContactPerson = "吴老板",
                            Name = "东莞长安机电市场",
                            Phone = "13133339999"
                        });
                });

            modelBuilder.Entity("PSI.Models.PurchaseOrder", b =>
                {
                    b.HasOne("PSI.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PSI.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("PSI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSI.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("PSI.Models.SaleOrder", b =>
                {
                    b.HasOne("PSI.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PSI.Models.SaleOrderDetail", b =>
                {
                    b.HasOne("PSI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSI.Models.SaleOrder", "SaleOrder")
                        .WithMany("Details")
                        .HasForeignKey("SaleOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("PSI.Models.Stock", b =>
                {
                    b.HasOne("PSI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PSI.Models.StockLog", b =>
                {
                    b.HasOne("PSI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PSI.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("PSI.Models.SaleOrder", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
